// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// Delta
SEXP Delta(const Eigen::Map<Eigen::MatrixXd> Info, const Eigen::Map<Eigen::VectorXd> S);
RcppExport SEXP _LFDR_Delta(SEXP InfoSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type Info(InfoSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(Delta(Info, S));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LFDR_Delta", (DL_FUNC) &_LFDR_Delta, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_LFDR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
