# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Newton-Raphson Update
#' 
#' 
#' @param Info Information matrix
#' @param S Score vector
#'   
Delta <- function(Info, S) {
    .Call(`_LFDR_Delta`, Info, S)
}

