# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix Matrix Product
#'
#' Calculates the product \eqn{AB}. 
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix.
#' @export
MMP <- function(A, B) {
    .Call('_LFDR_MMP', PACKAGE = 'LFDR', A, B)
}

#' Matrix Inner Product
#'
#' Calculates the inner product \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
matIP <- function(A, B) {
    .Call('_LFDR_matIP', PACKAGE = 'LFDR', A, B)
}

#' Matrix Inverse
#'
#' Calcualtes \eqn{A^{-1}}.
#' 
#' @param A Numeric matrix.
#' @return A numeric matrix. 
matInv <- function(A) {
    .Call('_LFDR_matInv', PACKAGE = 'LFDR', A)
}

#' Matrix Determinant
#'
#' Calculates the determinant of matrix \eqn{A}. 
#'
#' @param A Numeric matrix.
#' @return Scalar. 
det <- function(A) {
    .Call('_LFDR_det', PACKAGE = 'LFDR', A)
}

#' Matrix Quadratic Form
#' 
#' Calculates the quadratic form \eqn{X'AX}.
#' 
#' @param X Numeric matrix.
#' @param A Numeric matrix.
#' @return Numeric matrix
matQF <- function(X, A) {
    .Call('_LFDR_matQF', PACKAGE = 'LFDR', X, A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{bb}-I_{ba}I_{aa}^{-1}I_{ab}}. 
#'
#' @param Ibb Information of target parameter
#' @param Iaa Information of nuisance parameter
#' @param Iba Cross information between target and nuisance parameters
#' @return Numeric matrix. 
SchurC <- function(Ibb, Iaa, Iba) {
    .Call('_LFDR_SchurC', PACKAGE = 'LFDR', Ibb, Iaa, Iba)
}

